esphome:
  name: rc-car-32cam

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "7b6d7ce8387195504fbda6b1c313106a"

wifi:
  ssid: YOUR_WIFI_NAME
  password: YOUR_PASSWORD

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rc-Car-32Cam Fallback Hotspot"
    password: "YOUR_PASSWORD"

captive_portal:

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  name: RC Car32Cam

light:
 - platform: binary 
   output: led
   name: led_rc_car_camera
 
output:
- platform: gpio
  pin: GPIO4
  id: led

text_sensor:
 - platform: version
   name: "RC Car32Cam ESPHome Version" 

switch:
 - platform: restart
   name: "RC Car32Cam Restart" 
  
binary_sensor:
 - platform: status
   name: "RC Car32Cam Status" 

sensor:
 - platform: uptime
   name: Uptime Sensor
 - platform: wifi_signal
   name: "RC Car32Cam WiFi Signal Sensor" 
   update_interval: 60s
