esphome:
  name: rc-car

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API

ota:
  password: "xxxxxxxxxxxxxxx"

wifi:
  ssid: YOUR_WIFI_NAME
  password: YOUR_PASSWORD

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rc-Car Fallback Hotspot"
    password: "YOUR_PASSWORD"
    
# 192.168...

#web_server:
#  port: 80

captive_portal:

switch:
  - platform: gpio
    pin: GPIO15
    name: "input1"
    id: input1
  - platform: gpio
    pin: GPIO14
    name: "input2"
    id: input2
  - platform: gpio
    pin: GPIO12
    name: "input3"
    id: input3
  - platform: gpio
    pin: GPIO13
    name: "input4"
    id: input4
#  - platform: gpio
#    pin: 
#      number: GPIO0
#      inverted: true
#    name: "rc 8266 led"
#    id: ledinput

#web_server:
#  port: 80
  
api:
  services:
    - service: control_servo_x
      variables:
        level: float
      then:
        - servo.write:
            id: servo_x
            level: !lambda 'return level / 100.0;'
    - service: control_servo_y
      variables:
        level: float
      then:
        - servo.write:
            id: servo_y
            level: !lambda 'return level / 100.0;'
    - service: control_servo_x_2
      variables:
        level: float
      then:
        - servo.write:
            id: servo_x2
            level: !lambda 'return level / 100.0;'
light:
  - platform: monochromatic
    name: "RC Leds cámara"
    output: leds_rccam
# Example speed usage as a light
  - platform: monochromatic
    output: pwm_speed_car
    name: "RC OnOff and Car Speed"
  - platform: monochromatic
    name: "RC Leds frontales"
    output: leds_rcfront
  - platform: monochromatic
    name: "RC Leds detrás"
    output: leds_rcback
  - platform: monochromatic
    name: "RC Led marcha atrás"
    output: led_rcbackward
 

sensor:
  - platform: adc
    pin: A0
    id: "LIION"
    name: "RC adc0 Voltage"
    update_interval: 10s
    accuracy_decimals: 3
    filters:
      - multiply: 4
    
      
output:
  - id: leds_rccam
    platform: esp8266_pwm
    pin: GPIO0
    inverted: true
  - platform: esp8266_pwm
    pin: GPIO16
    frequency: 1000 Hz
    id: pwm_speed_car
  - platform: esp8266_pwm
    id: leds_rcfront
    pin: GPIO1
    inverted: true
  - platform: esp8266_pwm
    id: leds_rcback
    inverted: true
    pin: GPIO10
#GPIO10 pin can't dim light
  - id: led_rcbackward
    platform: esp8266_pwm
    pin: GPIO2
    inverted: true
  - platform: esp8266_pwm
    id: pwm_output
    pin: GPIO5
    frequency: 50 Hz
  - platform: esp8266_pwm
    id: pwm_output2
    pin: GPIO4
    frequency: 50 Hz
  - platform: esp8266_pwm
    id: pwm_output3
    pin: GPIO3
    frequency: 50 Hz
#  - platform: esp8266_pwm  # or platform: ledc if is on esp32


servo:
  - id: servo_x
    output: pwm_output
  - id: servo_y
    output: pwm_output2
  - id: servo_x2
    output: pwm_output3
